version: "3.7"
services:
  app:
    image: ${APP_NAME}:${TAG}
    container_name: ${APP_NAME}
    build:
      context: ./temp-button
      dockerfile: Dockerfile
    volumes:
      - ./temp-button/:/var/www/app
    command: sh -c './wait_for.sh db:3306 -- sh start.sh'
    networks:
      - temp_button_app_network
    expose:
      - 9000
    depends_on:
      - db
  
  web:
    container_name: ${APP_NAME}-web
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./temp-button:/var/www/app
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - temp_button_app_network

  
  db:
    container_name: ${APP_NAME}-db
    build: 
      context: ./
      dockerfile: ./docker/database/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/database/db:/var/lib/mysql
    networks:
      - temp_button_app_network
  
networks:
  temp_button_app_network:
    driver: bridge